### PR TITLE
Rename lib_installer.bs to lib_installer.sh

### PR DESCRIPTION
**Pull request by Cretezy**

### CODE REVIEW

**Comment by Zulban** [comment]
Any particular reason for your preference here..? I am curious if you have a reason to prefer one extension over another, or if you're just recommending I do what you're used to.

**Comment by Cretezy** [comment]
Literally never seen .bs. It's .sh or .bash.

**Comment by Cretezy** [comment]
And it's used for other things.

.bs
http://filext.com/file-extension/BS
http://www.openwith.org/file-extensions/bs/1400
http://www.file-extensions.org/bs-file-extension-printfox-pagefox-image-format

.sh
http://filext.com/file-extension/SH
http://www.openthefile.net/extension/sh
http://www.file-extensions.org/sh-file-extension

**Comment by Zulban** [comment]
Hmmm! I wonder if I ever merged these? This one I think I did.

Hope things are well... have you seen my latest project [chesscraft](http://www.chesscraft.ca)? What are you up to lately? Deleting old repos I guess ;)

**Comment by Cretezy** [comment]
Currently working for @aldo-dev, check out my profile for stuff I've been working on!

**Pull request closed without merging**
